In [2]:
# Module 1 Lab

import numpy as np
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer, util

# Matrix operations review
# First, generate three NumPy arrays with the following properties:
# - a 5 by 5 array of randomly generated integers with values from 0 through 9.
# - a 1 by 5 array of randomly generated integers with values from 0 through 9.
# - a 5 by 2 array of randomly generated integers with values from 0 through 9.

A = np.random.randint(0, 10, (5, 5))
B = np.random.randint(0, 10, 5)
C = np.random.randint(0, 10, (5, 2))

print(f"A = \n{A}\n")
print(f"B = \n{B}\n")
print(f"C = \n{C}")


/home/samlau/Python/StatisticsWithPython/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


A = 
[[6 0 6 5 8]
 [9 4 2 3 7]
 [4 0 3 8 8]
 [9 9 2 0 6]
 [4 8 7 3 8]]

B = 
[7 3 5 6 9]

C = 
[[0 4]
 [4 3]
 [2 4]
 [3 3]
 [7 8]]


In [3]:
# Next, translate each of the following calculations into code. Be mindful of which operators and NumPy functions you are using.

# Calculation A - compute the element-wise product of A with itself.
print(f"A * A = \n{A*A}\n")

# Calculation B - use broadcasting to calculate the element-wise product of A with B
print(f"A @ B = \n{A@B}\n")

# Calculation C - calculate the matrix product of A with C
print(f"A @ C = \n{A@C}\n")

# Calculation D - calculate the dot product of B with C
print(f"B @ C = \n{np.dot(B,C)}\n")


A * A = 
[[36  0 36 25 64]
 [81 16  4  9 49]
 [16  0  9 64 64]
 [81 81  4  0 36]
 [16 64 49  9 64]]

A @ B = 
[174 166 163 154 177]

A @ C = 
[[ 83 127]
 [ 78 121]
 [ 86 116]
 [ 82 119]
 [111 141]]

B @ C = 
[103 147]



In [6]:
# Applications with text embeddings
# We will now revisit using language models to calculate the similarities between sequences of text. Below is a corpus (a collection of texts) 
# that we will be embedding into a text vector space. This corpus is a selection of science trivia facts compiled by the BBC.

corpus = ["A cloud weighs around a million tonnes.",
          "Giraffes are 30 times more likely to get hit by lightning than people.",
          "Identical twins don't have the same fingerprints.",
          "Earth's rotation is changing speed.",
          "All the world's bacteria stacked on top of each other would stretch for 10 billion light-years.",
          "You can yo-you in space.",
          "Fish form orderly queues in emergencies.",
          "Most ginger cats are male.",
          "There's a planet made mostly from diamond.",
          "The biggest butterfly in the world has a 31 cm wingspan.",
          "The moon is shrinking.",
          "Flamingoes aren't born pink.",
          "Someone left a family photo on the Moon.",
          "Your brain burns 400-500 calories a day.",
          "You can't fold a piece of A4 paper more than 8 times.",
          "You can smell ants."
]


# Create an array representing the embeddings of each sentence in the corpora. You will need to instantiate a model using the sentence-transformers 
# library. As in the example from the video, use the all-MiniLM-L6-v2 model to encode the corpus. 
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(corpus) 
print(f"\n\nembedings.shape : {embeddings.shape}")
print(f"embedings :\n {embeddings}")



Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1236.44it/s, Materializing param=pooler.dense.weight]                             
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.




embedings.shape : (16, 384)
embedings :
 [[ 0.00871168  0.00482955  0.02127765 ... -0.0791853   0.03565254
   0.04289531]
 [ 0.03131773  0.00029476  0.03105445 ...  0.02931971  0.03899978
   0.06584611]
 [-0.11522342  0.01481626 -0.00279415 ...  0.00991059  0.06982809
   0.02879195]
 ...
 [ 0.05781776  0.000194    0.01398801 ...  0.08542574 -0.07259944
  -0.07348825]
 [-0.05619632  0.04949996 -0.00106818 ... -0.00834084  0.00759991
  -0.00594385]
 [ 0.06835493  0.00027368  0.0485975  ...  0.00864072 -0.01299392
  -0.02738279]]


In [7]:
# Now, create a target sentence that we want to find "neighbors" of in the embedding vector space. A good example might be "Give me a fact about an animal." 
target = "Give me a fact about an animal."
target_embedding = model.encode(target)

# Now we can calculate the dot product for each of the sentences with the target embedding.
dot_products = np.dot(embeddings, target_embedding)
print(f"\ndot_products :\n {dot_products}" )

# Finally, we can return the sentence with the highest dot product with the target.
most_similar_sentence = corpus[np.argmax(dot_products)]
print(f"\nMost similar sentence :\n {most_similar_sentence}")




dot_products :
 [0.16231804 0.31996214 0.08312652 0.11060212 0.1424796  0.12338172
 0.14369711 0.2518217  0.14231756 0.29128373 0.16527295 0.28924143
 0.11885389 0.00666183 0.07075185 0.27745754]

Most similar sentence :
 Giraffes are 30 times more likely to get hit by lightning than people.


In [9]:
# corpus sentences ranking in descending order of similarity

dot_products_desc = np.sort(dot_products)[::-1]
for n in dot_products_desc:
    idx_similar_sentence = np.where(dot_products == n)[0]
    print(f"{n} \t-> \t{corpus[idx_similar_sentence[0]]}")



0.31996214389801025 	-> 	Giraffes are 30 times more likely to get hit by lightning than people.
0.2912837266921997 	-> 	The biggest butterfly in the world has a 31 cm wingspan.
0.2892414331436157 	-> 	Flamingoes aren't born pink.
0.2774575352668762 	-> 	You can smell ants.
0.25182169675827026 	-> 	Most ginger cats are male.
0.16527295112609863 	-> 	The moon is shrinking.
0.16231803596019745 	-> 	A cloud weighs around a million tonnes.
0.1436971127986908 	-> 	Fish form orderly queues in emergencies.
0.14247959852218628 	-> 	All the world's bacteria stacked on top of each other would stretch for 10 billion light-years.
0.14231756329536438 	-> 	There's a planet made mostly from diamond.
0.12338171899318695 	-> 	You can yo-you in space.
0.11885388940572739 	-> 	Someone left a family photo on the Moon.
0.11060211807489395 	-> 	Earth's rotation is changing speed.
0.08312651515007019 	-> 	Identical twins don't have the same fingerprints.
0.0707518458366394 	-> 	You can't fold a piece of A4 pa

In [10]:
# Experiment with a different embedding model
# What if you had chosen a different embedding model for the texts? Would you still get similar results?
# First, choose another model available from the SentenceTransformers library, and then instantiate that model (you might give it a name like modelB). 

model_name = 'paraphrase-albert-small-v2'
model = SentenceTransformer(model_name)
embeddings = model.encode(corpus) 
target = "Give me a fact about an animal."
target_embedding = model.encode(target)
dot_products = np.dot(embeddings, target_embedding)
most_similar_sentence = corpus[np.argmax(dot_products)]
print(f"\n\nModel Name : {model_name}")
print(f"Target sentence : {target}")
print(f"\nMost similar sentence :\n {most_similar_sentence}\n\n")

dot_products_desc = np.sort(dot_products)[::-1]
for n in dot_products_desc:
    idx_similar_sentence = np.where(dot_products == n)[0]
    print(f"{n} \t-> \t{corpus[idx_similar_sentence[0]]}")



Loading weights: 100%|██████████| 25/25 [00:00<00:00, 1229.29it/s, Materializing param=pooler.weight]                                                             
AlbertModel LOAD REPORT from: sentence-transformers/paraphrase-albert-small-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.




Model Name : paraphrase-albert-small-v2
Target sentence : Give me a fact about an animal.

Most similar sentence :
 Most ginger cats are male.


70.15880584716797 	-> 	Most ginger cats are male.
58.54023742675781 	-> 	You can smell ants.
54.222267150878906 	-> 	The biggest butterfly in the world has a 31 cm wingspan.
51.343467712402344 	-> 	Giraffes are 30 times more likely to get hit by lightning than people.
47.705196380615234 	-> 	Flamingoes aren't born pink.
45.06638717651367 	-> 	A cloud weighs around a million tonnes.
39.68830871582031 	-> 	Fish form orderly queues in emergencies.
36.61774444580078 	-> 	There's a planet made mostly from diamond.
27.584434509277344 	-> 	All the world's bacteria stacked on top of each other would stretch for 10 billion light-years.
24.693683624267578 	-> 	You can yo-you in space.
18.04378890991211 	-> 	Identical twins don't have the same fingerprints.
5.370265483856201 	-> 	Your brain burns 400-500 calories a day.
4.479018688201904 	-> 	Someone l