In [ ]:
# Module 1 Lab

import numpy as np
import matplotlib.pyplot as plt

# Matrix operations review
# First, generate three NumPy arrays with the following properties:
# - a 5 by 5 array of randomly generated integers with values from 0 through 9.
# - a 1 by 5 array of randomly generated integers with values from 0 through 9.
# - a 5 by 2 array of randomly generated integers with values from 0 through 9.

A = np.random.randint(0, 10, (5, 5))
B = np.random.randint(0, 10, 5)
C = np.random.randint(0, 10, (5, 2))

print(f"A = \n{A}\n")
print(f"B = \n{B}\n")
print(f"C = \n{C}")


A = 
[[6 0 9 6 2]
 [4 2 5 4 9]
 [9 0 7 3 9]
 [2 9 8 6 0]
 [0 4 6 3 9]]

B = 
[0 0 4 0 7]

C = 
[[7 1]
 [1 5]
 [9 5]
 [4 6]
 [8 4]]


In [2]:
# Next, translate each of the following calculations into code. Be mindful of which operators and NumPy functions you are using.

# Calculation A - compute the element-wise product of A with itself.
print(f"A * A = \n{A*A}\n")

# Calculation B - use broadcasting to calculate the element-wise product of A with B
print(f"A @ B = \n{A@B}\n")

# Calculation C - calculate the matrix product of A with C
print(f"A @ C = \n{A@C}\n")

# Calculation D - calculate the dot product of B with C
print(f"B @ C = \n{np.dot(B,C)}\n")


A * A = 
[[36  0 81 36  4]
 [16  4 25 16 81]
 [81  0 49  9 81]
 [ 4 81 64 36  0]
 [ 0 16 36  9 81]]

A @ B = 
[50 83 91 32 87]

A @ C = 
[[163  95]
 [163  99]
 [210  98]
 [119 123]
 [142 104]]

B @ C = 
[92 48]



In [3]:
# Applications with text embeddings
# We will now revisit using language models to calculate the similarities between sequences of text. Below is a corpus (a collection of texts) 
# that we will be embedding into a text vector space. This corpus is a selection of science trivia facts compiled by the BBC.

corpus = ["A cloud weighs around a million tonnes.",
          "Giraffes are 30 times more likely to get hit by lightning than people.",
          "Identical twins don't have the same fingerprints.",
          "Earth's rotation is changing speed.",
          "All the world's bacteria stacked on top of each other would stretch for 10 billion light-years.",
          "You can yo-you in space.",
          "Fish form orderly queues in emergencies.",
          "Most ginger cats are male.",
          "There's a planet made mostly from diamond.",
          "The biggest butterfly in the world has a 31 cm wingspan.",
          "The moon is shrinking.",
          "Flamingoes aren't born pink.",
          "Someone left a family photo on the Moon.",
          "Your brain burns 400-500 calories a day.",
          "You can't fold a piece of A4 paper more than 8 times.",
          "You can smell ants."
]


# Create an array representing the embeddings of each sentence in the corpora. You will need to instantiate a model using the sentence-transformers 
# library. As in the example from the video, use the all-MiniLM-L6-v2 model to encode the corpus. 
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(corpus) 
print(f"\n\nembedings.shape : {embeddings.shape}")
print(f"embedings :\n {embeddings}")



NameError: name 'SentenceTransformer' is not defined

In [ ]:
# Now, create a target sentence that we want to find "neighbors" of in the embedding vector space. A good example might be "Give me a fact about an animal." 
target = "Give me a fact about an animal."
target_embedding = model.encode(target)

# Now we can calculate the dot product for each of the sentences with the target embedding.
dot_products = np.dot(embeddings, target_embedding)
print(f"\ndot_products :\n {dot_products}" )

# Finally, we can return the sentence with the highest dot product with the target.
most_similar_sentence = corpus[np.argmax(dot_products)]
print(f"\nMost similar sentence :\n {most_similar_sentence}")



In [ ]:
# corpus sentences ranking in descending order of similarity

dot_products_desc = np.sort(dot_products)[::-1]
for n in dot_products_desc:
    idx_similar_sentence = np.where(dot_products == n)[0]
    print(f"{n} \t-> \t{corpus[idx_similar_sentence[0]]}")



In [ ]:
# Experiment with a different embedding model
# What if you had chosen a different embedding model for the texts? Would you still get similar results?
# First, choose another model available from the SentenceTransformers library, and then instantiate that model (you might give it a name like modelB). 

model_name = 'paraphrase-albert-small-v2'
model = SentenceTransformer(model_name)
embeddings = model.encode(corpus) 
target = "Give me a fact about an animal."
target_embedding = model.encode(target)
dot_products = np.dot(embeddings, target_embedding)
most_similar_sentence = corpus[np.argmax(dot_products)]
print(f"\n\nModel Name : {model_name}")
print(f"Target sentence : {target}")
print(f"\nMost similar sentence :\n {most_similar_sentence}\n\n")

dot_products_desc = np.sort(dot_products)[::-1]
for n in dot_products_desc:
    idx_similar_sentence = np.where(dot_products == n)[0]
    print(f"{n} \t-> \t{corpus[idx_similar_sentence[0]]}")

